### PR TITLE
Added haml processing if defined.

### PR DESCRIPTION
**Pull request by marcelloma**
I use haml on my projects so I made this fork to be able to use haml on .coffee templates.
I don't know the solution is the best one though...

### CODE REVIEW

**Comment by markbates** [comment]
Hmm... yeah, not sure this is the best way. I would change erb_handler to just handler, have it check the file extension, then call the appropriate handler, if there is one. Does that make sense?

**Comment by marcelloma** [comment]
Then the file would be like 'foo.js.erb.coffee'?

**Comment by markbates** [comment]
foo.coffee.haml or foo.coffee.erb

**Comment by marcelloma** [comment]
What about the format? Doesnt the file need .js somewhere to handle .js requests?

**Comment by markbates** [comment]
no, it's already mapping js requests to coffee, so no need to duplicate that.

**Comment by marcelloma** [comment]
That does not seem to work for me.

Im getting: "Missing template offers/search, application/search with {:handlers=>[:erb, :builder, :coffee, :haml], :formats=>[:js, :html]"

My template is named 'search.coffee.haml'

Maybe I'm doing it wrong?

Where do we map coffee to handle js format requests?

**Comment by markbates** [comment]
sorry, my bad, the file format is foo.js.coffee. sorry about that.

**Comment by marcelloma** [comment]
Any idea of how to do that without using defined? maybe a configuration? Since I don't have the file type to distinguish haml from erb... I can at least make erb_handler and haml_handler one method.. but still use defined to check...

**Comment by marcelloma** [comment]
I've refactored to only one handler method, still I don`t see anything else that could be done to enhance how it decides which template to use(erb or haml)

I hope this is enough.

**Comment by brewster1134** [comment]
Because haml and coffeescript use the same `#{...}` interpolation syntax, doesn't this cause issues?

**Comment by marcelloma** [comment]
I did not realize that when I did the change. I think it would not work at all... Im not even using this anymore... closing.

**Pull request closed without merging**
